### ISSUE TITLE
cant play sas4

### ISSUE THREAD

**Issue by GeneralCragg** [GlennnM/FlashPrivateServer#5]
![image](https://github.com/user-attachments/assets/017793bf-c98c-4cbc-8f15-7019bb08b4dc)
 cant log into the game the starting laoding screen loads but then gets stuck on this logging screen it seems to do something with the account because if you go in as a guest it does let you in game but the issue is it doesnt let you move in game or anything its basicly a frozen frame nothing else

**Comment by GeneralCragg** [comment]
happens with other games as well

**Comment by GeneralCragg** [comment]
nvm works now guess it was a server issue sorry

**Comment by GlennnM** [comment]
I don't host the login servers, it was an NK issue and is fixed now, although the token issue which prevents a lot of people from logging in is ongoing.
